from telegram.ext import ConversationHandler
HEDEARS = 'HEDEARS'
TYPING = 'TYPING'
CURRENT_ATTRIBUTE = 'CURRENT_ATTRIBUTE'
SELECTING_ATTRIBUTE = 'SELECTING_ATTRIBUTE'
RESULT_OPERATION = 'RESULT_OPERATION'
REPEAT_OPERATION = 'REPEAT_OPERATION'
START_OVER = 'START_OVER'
END = ConversationHandler.END